export const AUTH_ENDPOINT = "/api/login";
export const FILM_ENDPOINT = "/api/hibernate/films";
export const FILM_RECHERCH = FILM_ENDPOINT+"/recherche";
export const FILM_RECHERCH_NOM = FILM_ENDPOINT+"/recherche/nom";
export const FILM_RECHERCH_GENRE = FILM_ENDPOINT+"/recherche/genre";
export const LOCATION_ENPOINT = FILM_ENDPOINT+'/locations';
export const FILM_BANDEANNONCE = FILM_ENDPOINT+'/bandeannonce'
export const ANALYTICS_STATS = "/api/hibernate/analytics/stats";
export const COTE_MOYENNE_FILM_CONSULTE=  '/api/hibernate/analytics/film/cote-moyenne';
export const CORRELATION_FILM_CONSULTE=  '/api/hibernate/analytics/film/correlation';