CREATE TABLE olap_Client(
    id_client NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nom VARCHAR(1000),
    groupe_age NUMBER,
    anciennete DATE,
    code_postal VARCHAR(1000),
    ville VARCHAR(1000),
    province VARCHAR(1000),

    CONSTRAINT olap_client_pk PRIMARY KEY (id_client)
);

CREATE TABLE olap_Film(
    id_film NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    titre VARCHAR(1000),
    annee_sortie NUMBER,
    pays NUMBER(1),
    action_g NUMBER(1),
    adventure_g NUMBER(1),
    comedy_g NUMBER(1),
    family_g NUMBER(1),
    romance_g NUMBER(1),
    drama_g NUMBER(1),
    animation_g NUMBER(1),
    fantasy_g NUMBER(1),
    biography_g NUMBER(1),
    thriller_g NUMBER(1),
    sci_fi_g NUMBER(1),
    crime_g NUMBER(1),
    sport_g NUMBER(1),
    horror_g NUMBER(1),
    film_noir_g NUMBER(1), 
    mystery_g NUMBER(1),
    western_g NUMBER(1),
    war_g NUMBER(1),
    musical_g NUMBER(1),
    documentary_g NUMBER(1),
    history_g NUMBER(1),
    music_g NUMBER(1), 

    CONSTRAINT olap_film_pk PRIMARY KEY (id_film)
);

CREATE TABLE olap_Temps(
    id_temps NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date_complete DATE,
    heure NUMBER,
    jour NUMBER,
    mois NUMBER,
    annee NUMBER,
    jour_de_semaine NUMBER,

    CONSTRAINT olap_temps_pk PRIMARY KEY (id_temps)
);

CREATE TABLE olap_Location(
    id_location NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_film NUMBER NOT NULL,
    id_client NUMBER NOT NULL,
    id_temps NUMBER NOT NULL,
    cote REAL,
    groupe_age_client NUMBER NOT NULL,
    province_client VARCHAR(1000) NOT NULL,
    jour_de_semaine NUMBER NOT NULL,
    mois NUMBER NOT NULL,
   
    CONSTRAINT film_fk FOREIGN KEY (id_film) REFERENCES olap_film(id_film),
    CONSTRAINT client_fk FOREIGN KEY (id_client) REFERENCES olap_client(id_client),
    CONSTRAINT temps_fk FOREIGN KEY (id_temps) REFERENCES olap_temps(id_temps)
);

DROP TABLE olap_Location;
DROP TABLE olap_Film;
DROP TABLE olap_Temps;
DROP TABLE olap_Client;